name: escape_room_application
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Existentes
  flutter_map: ^6.0.1
  flutter_map_marker_popup: ^6.1.2
  latlong2: ^0.9.0
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.0.0
  english_words: ^4.0.0
  animations: ^2.0.11
  lucide_icons: ^0.257.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/escape_rooms_seed.json
    - assets/escape_rooms_completo.json
    - assets/images/logo_escape_fem.png
    - assets/images/logo_escape_fem_FAV.png
    - assets/images/avatars/
    - assets/genres/
